-- ⚠️ HAND-EDITED MIGRATION — documented exception to .claude/rules/database.md
--
-- This migration was generated by drizzle-kit but its legacy-row INSERT
-- was hand-edited to backfill `routing_mode='direct'` for rows that existed
-- before the dual-mode-routing schema landed. Without the backfill, every
-- existing user's chat would break on upgrade (they were direct-to-Anthropic
-- before the column existed; defaulting to 'litellm' without a configured
-- LiteLLM base URL fails at chat-send time).
--
-- The schema default was also revised to 'direct' so future drizzle-kit
-- regenerations match this hand-edit. See:
--   - openspec/changes/remediate-dev-server-findings/design.md Decision 7
--   - .claude/rules/database.md "Allowed exceptions" section
--
-- If you regenerate this migration with `bun run db:generate`, check the
-- INSERT statement below matches the hand-edit. If drizzle-kit produces a
-- narrower INSERT (without the `routing_mode` literal), re-apply the
-- hand-edit and note the divergence in a PR comment.

PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_anthropic_accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_type` text DEFAULT 'claude-subscription' NOT NULL,
	`routing_mode` text DEFAULT 'direct' NOT NULL,
	`email` text,
	`display_name` text,
	`oauth_token` text,
	`api_key` text,
	`virtual_key` text,
	`model_sonnet` text,
	`model_haiku` text,
	`model_opus` text,
	`connected_at` integer,
	`last_used_at` integer,
	`desktop_user_id` text
);
--> statement-breakpoint
-- HAND-EDIT: backfill legacy rows with routing_mode='direct' explicitly.
-- Legacy rows pre-date the routing_mode column and were working
-- direct-to-Anthropic before this change. Defaulting them to 'direct'
-- (not the old hand-edit-proposed 'litellm') preserves their working
-- behavior through the upgrade. New rows get the same default via the
-- column DEFAULT above.
INSERT INTO `__new_anthropic_accounts`("id", "routing_mode", "email", "display_name", "oauth_token", "connected_at", "last_used_at", "desktop_user_id") SELECT "id", 'direct', "email", "display_name", "oauth_token", "connected_at", "last_used_at", "desktop_user_id" FROM `anthropic_accounts`;--> statement-breakpoint
DROP TABLE `anthropic_accounts`;--> statement-breakpoint
ALTER TABLE `__new_anthropic_accounts` RENAME TO `anthropic_accounts`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
