---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: 1code-api
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - "${APP_HOSTNAME}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: 1code-api
          port: 8000
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: 1code-api
          port: 8000
